/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentrecords;

import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;
import static studentrecords.Students.capitalize;

/**
 *
 * @author Joan
 */
public class Employees extends javax.swing.JPanel {
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    EmployeesView ev = new EmployeesView();
    EmployeesAdd ea = new EmployeesAdd();
    EmployeesEdit ee = new EmployeesEdit();
    
    /**
     * Creates new form Dashboard
     */
    public Employees() {
        initComponents();
        
        showDate();
        showTime();
        
        StudentCard.add(ev);
        StudentCard.add(ea);
        StudentCard.add(ee);
        
        ev.setVisible(false);
        ea.setVisible(false);
        ee.setVisible(false);
    }
    
    public void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MMM. dd, yyyy");
        String date = s.format(d);
        lblDate.setText(date);
    }
    
    public void showTime() {
        new Timer (0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                String time = s.format(d);
                lblTime.setText(time);
            }
        }).start();
    }
    
    public void populateTbl() {
        try {
            con = ConnectDB.Connect();
            ps = con.prepareStatement("SELECT * FROM vw_employee ORDER BY \"Last Name\"");
            rs = ps.executeQuery();
            ev.tblEmployees.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public int[] date(String dateString) {
        int month = Integer.parseInt(dateString.substring(0,2));
        int day = Integer.parseInt(dateString.substring(3,5));
        int year = Integer.parseInt(dateString.substring(6,10));
        return new int[] {month, day, year};
    }
    
    public static String capitalize(String name) {
        char[] nameArray = name.toCharArray();
        boolean foundSpace = true;
        
        for(int letter = 0; letter < nameArray.length; letter++) {
            if(Character.isLetter(nameArray[letter])) {
                nameArray[letter] = Character.toLowerCase(nameArray[letter]);
                if(foundSpace) {
                    nameArray[letter] = Character.toUpperCase(nameArray[letter]);
                    foundSpace = false;
                }
            }
            else
                foundSpace = true;
        }
        return String.valueOf(nameArray);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChangingScreen = new javax.swing.JPanel();
        lblEmployees = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlSearchAdd = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        pnlAddRec = new studentrecords.RoundedFrame();
        btnAddRec = new javax.swing.JLabel();
        pnlEditRec = new studentrecords.RoundedFrame();
        btnEditRec = new javax.swing.JLabel();
        lblEmployees1 = new javax.swing.JLabel();
        StudentCard = new javax.swing.JLayeredPane();
        lblDate1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        pnlChangingScreen.setBackground(new java.awt.Color(240, 241, 243));
        pnlChangingScreen.setPreferredSize(new java.awt.Dimension(1327, 797));

        lblEmployees.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEmployees.setText("Employees");

        jPanel2.setBackground(new java.awt.Color(157, 12, 12));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        lblDate.setBackground(new java.awt.Color(153, 153, 153));
        lblDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 0, 0));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setText("MMM. dd, yyyy");
        lblDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTime.setBackground(new java.awt.Color(153, 153, 153));
        lblTime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 0));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("hh:mm:ss");
        lblTime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlSearchAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-search-30 (1).png"))); // NOI18N

        txtSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(204, 204, 204));
        txtSearch.setText("Search");
        txtSearch.setBorder(null);
        txtSearch.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtSearch.setSelectionColor(new java.awt.Color(239, 225, 225));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        pnlAddRec.setBackground(new java.awt.Color(157, 12, 12));

        btnAddRec.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddRec.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddRec.setText("Add a New Record");
        btnAddRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddRecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddRecMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAddRecLayout = new javax.swing.GroupLayout(pnlAddRec);
        pnlAddRec.setLayout(pnlAddRecLayout);
        pnlAddRecLayout.setHorizontalGroup(
            pnlAddRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddRecLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddRec, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAddRecLayout.setVerticalGroup(
            pnlAddRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddRec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        pnlEditRec.setBackground(new java.awt.Color(0, 102, 153));

        btnEditRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-edit-25.png"))); // NOI18N
        btnEditRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditRecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditRecMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEditRecLayout = new javax.swing.GroupLayout(pnlEditRec);
        pnlEditRec.setLayout(pnlEditRecLayout);
        pnlEditRecLayout.setHorizontalGroup(
            pnlEditRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditRec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );
        pnlEditRecLayout.setVerticalGroup(
            pnlEditRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlSearchAddLayout = new javax.swing.GroupLayout(pnlSearchAdd);
        pnlSearchAdd.setLayout(pnlSearchAddLayout);
        pnlSearchAddLayout.setHorizontalGroup(
            pnlSearchAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 498, Short.MAX_VALUE)
                .addComponent(pnlEditRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAddRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnlSearchAddLayout.setVerticalGroup(
            pnlSearchAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSearchAddLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pnlSearchAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAddRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEditRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblEmployees1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmployees1.setForeground(new java.awt.Color(204, 204, 204));
        lblEmployees1.setText("|   View Employee Records");

        StudentCard.setLayout(new java.awt.CardLayout());

        lblDate1.setBackground(new java.awt.Color(153, 153, 153));
        lblDate1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDate1.setForeground(new java.awt.Color(204, 204, 204));
        lblDate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate1.setText("Date & Time");
        lblDate1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlChangingScreenLayout = new javax.swing.GroupLayout(pnlChangingScreen);
        pnlChangingScreen.setLayout(pnlChangingScreenLayout);
        pnlChangingScreenLayout.setHorizontalGroup(
            pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangingScreenLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSearchAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlChangingScreenLayout.createSequentialGroup()
                        .addGroup(pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChangingScreenLayout.createSequentialGroup()
                                .addComponent(lblEmployees)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmployees1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDate1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(StudentCard, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(40, 40, 40))
        );
        pnlChangingScreenLayout.setVerticalGroup(
            pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangingScreenLayout.createSequentialGroup()
                .addGroup(pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlChangingScreenLayout.createSequentialGroup()
                        .addGroup(pnlChangingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployees)
                            .addComponent(lblEmployees1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlChangingScreenLayout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addGap(3, 3, 3)
                        .addComponent(lblTime))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(pnlSearchAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StudentCard, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChangingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChangingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRecMouseEntered
        // TODO add your handling code here:
        pnlAddRec.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnAddRecMouseEntered

    private void btnAddRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRecMouseExited
        // TODO add your handling code here:
        pnlAddRec.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnAddRecMouseExited

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if(btnAddRec.getText().equals("Add a New Record") && txtSearch.getText().equals("Search")) {
            txtSearch.setText("");
            txtSearch.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if(btnAddRec.getText().equals("Add a New Record") && txtSearch.getText().equals("")) {
            txtSearch.setText("Search");
            txtSearch.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void btnAddRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRecMouseClicked
        // TODO add your handling code here:
        if(btnAddRec.getText().equals("Add a New Record")) {
            ev.setVisible(false);
            ea.setVisible(true);
            btnAddRec.setText("View Records");
            lblEmployees1.setText("|   Add New Employee Record");
            txtSearch.setText("");
            txtSearch.setEditable(false);
            txtSearch.setFocusable(false);
            ea.txtDateResigned.setText("");
        } else if(btnAddRec.getText().equals("View Records")) {
            populateTbl();
            ev.clearFields();
            ev.setVisible(true);
            ee.setVisible(false);
            ea.setVisible(false);
            btnAddRec.setText("Add a New Record");
            lblEmployees1.setText("|   View Employee Records");
            txtSearch.setEditable(true);
            txtSearch.setFocusable(true);
            txtSearch.setForeground(Color.black);
        }
    }//GEN-LAST:event_btnAddRecMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        try {
            con = ConnectDB.Connect();
//            String search = txtSearch.getText().substring(0,1).toUpperCase();
            ps = con.prepareStatement("SELECT * FROM employee WHERE employee_id LIKE '%"+txtSearch.getText().toUpperCase()+"%'"
                    + "OR lastname LIKE '%"+capitalize(txtSearch.getText())+"%'"
                    + "OR firstname LIKE '%"+capitalize(txtSearch.getText())+"%'"
                    + "OR email LIKE '"+txtSearch.getText().toLowerCase()+"%'"
                    + "OR gender LIKE '"+txtSearch.getText().toUpperCase()+"'"
                    + "OR cp_num LIKE '"+txtSearch.getText()+"%'"
                    + "OR address LIKE '%"+capitalize(txtSearch.getText())+"%'"
                    + "OR birthday LIKE '%"+txtSearch.getText()+"%'"
                    + "OR date_started LIKE '%"+txtSearch.getText()+"%'"
                    + "OR date_resigned LIKE '%"+txtSearch.getText()+"%'"
                    + "OR status LIKE '"+txtSearch.getText().toUpperCase()+"'");
            rs = ps.executeQuery();
            ev.tblEmployees.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
            ps.close();
            rs.close();
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnEditRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditRecMouseExited
        // TODO add your handling code here:
        pnlEditRec.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnEditRecMouseExited

    private void btnEditRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditRecMouseEntered
        // TODO add your handling code here:
        pnlEditRec.setBackground(new Color(0,79,119));
    }//GEN-LAST:event_btnEditRecMouseEntered

    private void btnEditRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditRecMouseClicked
        // TODO add your handling code here:
        if(btnAddRec.getText().equals("Add a New Record")) {
            if(!ev.txtEmployeeID.getText().equals("")) {
                ea.setVisible(false);
                ev.setVisible(false);
                ee.setVisible(true);
                btnAddRec.setText("View Records");
                lblEmployees1.setText("|   Update Employee Records");
                txtSearch.setText("");
                txtSearch.setEditable(false);
                txtSearch.setFocusable(false);
                ee.txtEmployeeID.setEditable(false);
                ee.txtEmployeeID.setFocusable(false);
                int[] dateBDay = date(ev.txtBday.getText());
                ee.dateChooser.setSelectedDate(new SelectedDate(dateBDay[1], dateBDay[0], dateBDay[2]));
                int[] dateStarted = date(ev.txtDateStarted.getText());
                ee.dateChooser1.setSelectedDate(new SelectedDate(dateStarted[1], dateStarted[0], dateStarted[2]));
                ee.imgEmployee.setIcon(ev.imgEmployee.getIcon());

                Object val = ev.txtDateResigned.getText();
                if (val != null && !val.toString().isBlank()) {
                    String dateRes = val.toString().trim();
                    int[] dateResigned = date(dateRes);
                    ee.dateChooser2.setSelectedDate(new SelectedDate(dateResigned[1], dateResigned[0], dateResigned[2]));
                    ee.txtDateResigned1.setText(dateRes);
                    ee.txtDateResigned.setText(dateRes);
                } else {
                    ee.dateChooser2.toDay();
                    ee.txtDateResigned1.setText(null);
                    ee.txtDateResigned.setText(null);
                }

                ee.txtEmployeeID1.setText(ev.txtEmployeeID.getText());         ee.txtEmployeeID.setText(ev.txtEmployeeID.getText());
                ee.txtLastName1.setText(ev.txtLastName.getText());            ee.txtLastName.setText(ev.txtLastName.getText());
                ee.txtFirstName.setText(ev.txtFirstName.getText());           ee.txtGivenName.setText(ev.txtFirstName.getText());         
                ee.txtEmail1.setText(ev.txtEmail.getText());                  ee.txtEmail.setText(ev.txtEmail.getText());
                ee.txtMobileNum.setText(ev.txtMobileNum.getText());           ee.txtMobileNumber.setText(ev.txtMobileNum.getText().substring(1, ev.txtMobileNum.getText().length()));
                ee.txtAddress1.setText(ev.txtAddress.getText());              ee.txtAddress.setText(ev.txtAddress.getText());
                ee.txtBday1.setText(ev.txtBday.getText());                    ee.txtBday.setText(ev.txtBday.getText());
                ee.txtDateStarted1.setText(ev.txtDateStarted.getText());      ee.txtDateStarted.setText(ev.txtDateStarted.getText());
                ee.txtGender.setText(ev.txtGender.getText());                 ee.cmbGender.setSelectedItem(ev.txtGender.getText());
                ee.txtStatus.setText(ev.txtStatus.getText());                 ee.cmbStatus.setSelectedItem(ev.txtStatus.getText());
            } else 
                JOptionPane.showMessageDialog(null, "No record found! Choose a record to edit.");
        } else
            JOptionPane.showMessageDialog(null, "You are currently editing a record.");
    }//GEN-LAST:event_btnEditRecMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane StudentCard;
    private javax.swing.JLabel btnAddRec;
    private javax.swing.JLabel btnEditRec;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblEmployees1;
    private javax.swing.JLabel lblTime;
    private studentrecords.RoundedFrame pnlAddRec;
    private javax.swing.JPanel pnlChangingScreen;
    private studentrecords.RoundedFrame pnlEditRec;
    private javax.swing.JPanel pnlSearchAdd;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
