/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package studentrecords;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JTable;
import static java.lang.System.exit;

/**
 *
 * @author Joan
 */
public class MainScreen extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    Dashboard db = new Dashboard();
    Students st = new Students();
    Employees em = new Employees();
    SYSem sy = new SYSem();
    Colleges cl = new Colleges();
    Courses cs = new Courses();
    CoursesView csv = new CoursesView();
    Subjects sj = new Subjects();
    StudentGrades sg = new StudentGrades();
    SubjectSchedule ss = new SubjectSchedule();
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        MSCard.add(db);
        MSCard.add(st);
        MSCard.add(em);
        MSCard.add(sy);
        MSCard.add(cl);
        MSCard.add(cs);
        MSCard.add(sj);
        MSCard.add(sg);
        MSCard.add(ss);
        
        
        db.setVisible(false);
        st.setVisible(false);
        em.setVisible(false);
        sy.setVisible(false);
        cl.setVisible(false);
        cs.setVisible(false);
        sj.setVisible(false);
        sg.setVisible(false);
        ss.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        pnlMinimize = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        headerLogo = new javax.swing.JLabel();
        headerTitle = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblMenuHeader = new javax.swing.JLabel();
        pnlDashboard = new studentrecords.RoundedFrame();
        btnDashboard = new javax.swing.JLabel();
        pnlStudents = new studentrecords.RoundedFrame();
        btnStudents = new javax.swing.JLabel();
        pnlEmployees = new studentrecords.RoundedFrame();
        btnEmployees = new javax.swing.JLabel();
        pnlSYSem = new studentrecords.RoundedFrame();
        btnSYSem = new javax.swing.JLabel();
        pnlColleges = new studentrecords.RoundedFrame();
        btnColleges = new javax.swing.JLabel();
        pnlCourses = new studentrecords.RoundedFrame();
        btnCourses = new javax.swing.JLabel();
        pnlSubjects = new studentrecords.RoundedFrame();
        btnSubjects = new javax.swing.JLabel();
        pnlSubjSched = new studentrecords.RoundedFrame();
        btnSubjSched = new javax.swing.JLabel();
        pnlStudGrade = new studentrecords.RoundedFrame();
        btnStudGrade = new javax.swing.JLabel();
        MSCard = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1524, 836));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlMainScreen.setBackground(new java.awt.Color(240, 241, 243));

        pnlHeader.setBackground(new java.awt.Color(240, 241, 243));

        pnlExit.setBackground(new java.awt.Color(240, 241, 243));

        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("╳");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMinimize.setBackground(new java.awt.Color(240, 241, 243));

        btnMinimize.setForeground(new java.awt.Color(0, 0, 0));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("__");
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMinimizeLayout = new javax.swing.GroupLayout(pnlMinimize);
        pnlMinimize.setLayout(pnlMinimizeLayout);
        pnlMinimizeLayout.setHorizontalGroup(
            pnlMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );
        pnlMinimizeLayout.setVerticalGroup(
            pnlMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        headerLogo.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        headerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/plm logo.png"))); // NOI18N
        headerLogo.setIconTextGap(10);

        headerTitle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        headerTitle.setText("PLM Information Management System");
        headerTitle.setIconTextGap(10);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(headerLogo)
                .addGap(8, 8, 8)
                .addComponent(headerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLogo)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(157, 12, 12));

        lblMenuHeader.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMenuHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/plm logo 40px.png"))); // NOI18N
        lblMenuHeader.setText("PLM IMS");
        lblMenuHeader.setIconTextGap(20);

        pnlDashboard.setBackground(new java.awt.Color(135, 10, 10));

        btnDashboard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-dashboard-layout-25 (1).png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setIconTextGap(15);
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlStudents.setBackground(new java.awt.Color(157, 12, 12));

        btnStudents.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-students-25.png"))); // NOI18N
        btnStudents.setText("Students");
        btnStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudents.setIconTextGap(15);
        btnStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlStudentsLayout = new javax.swing.GroupLayout(pnlStudents);
        pnlStudents.setLayout(pnlStudentsLayout);
        pnlStudentsLayout.setHorizontalGroup(
            pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlStudentsLayout.setVerticalGroup(
            pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlEmployees.setBackground(new java.awt.Color(157, 12, 12));

        btnEmployees.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEmployees.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-teacher-25.png"))); // NOI18N
        btnEmployees.setText("Employees");
        btnEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployees.setIconTextGap(15);
        btnEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmployeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEmployeesLayout = new javax.swing.GroupLayout(pnlEmployees);
        pnlEmployees.setLayout(pnlEmployeesLayout);
        pnlEmployeesLayout.setHorizontalGroup(
            pnlEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmployeesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEmployeesLayout.setVerticalGroup(
            pnlEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlSYSem.setBackground(new java.awt.Color(157, 12, 12));

        btnSYSem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSYSem.setForeground(new java.awt.Color(255, 255, 255));
        btnSYSem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-calendar-25.png"))); // NOI18N
        btnSYSem.setText("S.Y. & Semester");
        btnSYSem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSYSem.setIconTextGap(15);
        btnSYSem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSYSemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSYSemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSYSemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSYSemLayout = new javax.swing.GroupLayout(pnlSYSem);
        pnlSYSem.setLayout(pnlSYSemLayout);
        pnlSYSemLayout.setHorizontalGroup(
            pnlSYSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSYSemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSYSem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSYSemLayout.setVerticalGroup(
            pnlSYSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSYSem, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlColleges.setBackground(new java.awt.Color(157, 12, 12));

        btnColleges.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnColleges.setForeground(new java.awt.Color(255, 255, 255));
        btnColleges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-college-25.png"))); // NOI18N
        btnColleges.setText("Colleges");
        btnColleges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColleges.setIconTextGap(15);
        btnColleges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCollegesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCollegesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCollegesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlCollegesLayout = new javax.swing.GroupLayout(pnlColleges);
        pnlColleges.setLayout(pnlCollegesLayout);
        pnlCollegesLayout.setHorizontalGroup(
            pnlCollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCollegesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnColleges, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCollegesLayout.setVerticalGroup(
            pnlCollegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnColleges, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlCourses.setBackground(new java.awt.Color(157, 12, 12));

        btnCourses.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-course-25.png"))); // NOI18N
        btnCourses.setText("Courses");
        btnCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCourses.setIconTextGap(15);
        btnCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCoursesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlCoursesLayout = new javax.swing.GroupLayout(pnlCourses);
        pnlCourses.setLayout(pnlCoursesLayout);
        pnlCoursesLayout.setHorizontalGroup(
            pnlCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoursesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCoursesLayout.setVerticalGroup(
            pnlCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlSubjects.setBackground(new java.awt.Color(157, 12, 12));

        btnSubjects.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSubjects.setForeground(new java.awt.Color(255, 255, 255));
        btnSubjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-biology-book-25.png"))); // NOI18N
        btnSubjects.setText("Subjects");
        btnSubjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubjects.setIconTextGap(15);
        btnSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSubjectsLayout = new javax.swing.GroupLayout(pnlSubjects);
        pnlSubjects.setLayout(pnlSubjectsLayout);
        pnlSubjectsLayout.setHorizontalGroup(
            pnlSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSubjectsLayout.setVerticalGroup(
            pnlSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlSubjSched.setBackground(new java.awt.Color(157, 12, 12));

        btnSubjSched.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSubjSched.setForeground(new java.awt.Color(255, 255, 255));
        btnSubjSched.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-schedule-25.png"))); // NOI18N
        btnSubjSched.setText("Subject Schedule");
        btnSubjSched.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubjSched.setIconTextGap(15);
        btnSubjSched.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubjSchedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjSchedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubjSchedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSubjSchedLayout = new javax.swing.GroupLayout(pnlSubjSched);
        pnlSubjSched.setLayout(pnlSubjSchedLayout);
        pnlSubjSchedLayout.setHorizontalGroup(
            pnlSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjSchedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubjSched, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSubjSchedLayout.setVerticalGroup(
            pnlSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSubjSched, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnlStudGrade.setBackground(new java.awt.Color(157, 12, 12));

        btnStudGrade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnStudGrade.setForeground(new java.awt.Color(255, 255, 255));
        btnStudGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecords/Images/icons8-grade-25.png"))); // NOI18N
        btnStudGrade.setText("Student Grade");
        btnStudGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudGrade.setIconTextGap(15);
        btnStudGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudGradeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudGradeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudGradeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlStudGradeLayout = new javax.swing.GroupLayout(pnlStudGrade);
        pnlStudGrade.setLayout(pnlStudGradeLayout);
        pnlStudGradeLayout.setHorizontalGroup(
            pnlStudGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudGradeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStudGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlStudGradeLayout.setVerticalGroup(
            pnlStudGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStudGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSYSem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlColleges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSubjSched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(lblMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSYSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlColleges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubjSched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStudGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MSCard.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(MSCard, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainScreenLayout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(MSCard, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        pnlExit.setBackground(new Color(189,4,4));
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        pnlExit.setBackground(new Color(244,244,244));
        btnExit.setForeground(Color.black);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
//        this.setExtendedState(MainScreen.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        pnlMinimize.setBackground(new Color(220,220,220));
        btnMinimize.setForeground(Color.black);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        pnlMinimize.setBackground(new Color(244,244,244));
        btnMinimize.setForeground(Color.black);
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
        db.setVisible(true);
        st.setVisible(false);
        em.setVisible(false);
        sy.setVisible(false);
        cl.setVisible(false);
        cs.setVisible(false);
        sj.setVisible(false);
        sg.setVisible(false);
        ss.setVisible(false);
        pnlDashboard.setBackground(new Color(135, 10, 10));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
        
        try {
            con = ConnectDB.Connect();
            ps = con.prepareStatement("SELECT COUNT(*) FROM student WHERE status = 'A'");
            rs = ps.executeQuery();
            if(rs.next()) {
                int studentCount = rs.getInt(1);
                db.totalStudents.setText(String.valueOf(studentCount));
            }
            rs.close();
            ps.close();
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
        
        try {
            con = ConnectDB.Connect();
            ps = con.prepareStatement("SELECT COUNT(*) FROM employee WHERE status = 'A'");
            rs = ps.executeQuery();
            if(rs.next()) {
                int employeeCount = rs.getInt(1);
                db.totalEmployees.setText(String.valueOf(employeeCount));
            }
            rs.close();
            ps.close();
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
        
        try {
            con = ConnectDB.Connect();
            ps = con.prepareStatement("SELECT COUNT(*) FROM course WHERE status = 'A'");
            rs = ps.executeQuery();
            if(rs.next()) {
                int courseCount = rs.getInt(1);
                db.totalCourses.setText(String.valueOf(courseCount));
            }
            rs.close();
            ps.close();
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
        
        try {
            con = ConnectDB.Connect();
            ps = con.prepareStatement("SELECT COUNT(*) FROM college WHERE status = 'A'");
            rs = ps.executeQuery();
            if(rs.next()) {
                int collegeCount = rs.getInt(1);
                db.totalColleges.setText(String.valueOf(collegeCount));
            }
            rs.close();
            ps.close();
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(157,12,12)))
            pnlDashboard.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        // TODO add your handling code here:
        if(pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlDashboard.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseClicked
        // TODO add your handling code here:
        st.setVisible(true);
        db.setVisible(false);
        em.setVisible(false);
        sy.setVisible(false);
        cl.setVisible(false);
        cs.setVisible(false);
        sj.setVisible(false);
        sg.setVisible(false);
        ss.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(135, 10, 10));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnStudentsMouseClicked

    private void btnStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseEntered
        // TODO add your handling code here:
        if(pnlStudents.getBackground().equals(new Color(157,12,12)))
            pnlStudents.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnStudentsMouseEntered

    private void btnStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlStudents.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnStudentsMouseExited

    private void btnEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMouseClicked
        // TODO add your handling code here:
        em.setVisible(true);
        st.setVisible(false);
        db.setVisible(false);
        sy.setVisible(false);
        cl.setVisible(false);
        sg.setVisible(false);
        cs.setVisible(false);
        sj.setVisible(false);
        ss.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(135, 10, 10));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnEmployeesMouseClicked

    private void btnEmployeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMouseEntered
        // TODO add your handling code here:
        if(pnlEmployees.getBackground().equals(new Color(157,12,12)))
            pnlEmployees.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnEmployeesMouseEntered

    private void btnEmployeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlEmployees.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnEmployeesMouseExited

    private void btnSYSemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSYSemMouseClicked
        // TODO add your handling code here:
        sy.setVisible(true);
        cs.setVisible(false);
        sj.setVisible(false);
        em.setVisible(false);
        st.setVisible(false);
        sg.setVisible(false);
        db.setVisible(false);
        cl.setVisible(false);
        ss.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(135, 10, 10));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnSYSemMouseClicked

    private void btnSYSemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSYSemMouseEntered
        // TODO add your handling code here:
        if(pnlSYSem.getBackground().equals(new Color(157,12,12)))
            pnlSYSem.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnSYSemMouseEntered

    private void btnSYSemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSYSemMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlSYSem.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnSYSemMouseExited

    private void btnCollegesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegesMouseClicked
        // TODO add your handling code here:
        cl.setVisible(true);
        em.setVisible(false);
        sy.setVisible(false);
        st.setVisible(false);
        db.setVisible(false);
        cs.setVisible(false);
        sj.setVisible(false);
        sg.setVisible(false);
        ss.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(135, 10, 10));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnCollegesMouseClicked

    private void btnCollegesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegesMouseEntered
        // TODO add your handling code here:
        if(pnlColleges.getBackground().equals(new Color(157,12,12)))
            pnlColleges.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnCollegesMouseEntered

    private void btnCollegesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegesMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlColleges.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnCollegesMouseExited

    private void btnCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoursesMouseClicked
        // TODO add your handling code here:
        cs.setVisible(true);
        csv.populateCmbCollege();
        em.setVisible(false);
        sy.setVisible(false);
        st.setVisible(false);
        db.setVisible(false);
        cl.setVisible(false);
        sj.setVisible(false);
        sg.setVisible(false);
        ss.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(135, 10, 10));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnCoursesMouseClicked

    private void btnCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoursesMouseEntered
        // TODO add your handling code here:
        if(pnlCourses.getBackground().equals(new Color(157,12,12)))
            pnlCourses.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnCoursesMouseEntered

    private void btnCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoursesMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlCourses.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnCoursesMouseExited

    private void btnSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseClicked
        // TODO add your handling code here:
        sj.setVisible(true);
        ss.setVisible(false);
        cs.setVisible(false);
        sg.setVisible(false);
        em.setVisible(false);
        sy.setVisible(false);
        st.setVisible(false);
        db.setVisible(false);
        cl.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(135, 10, 10));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnSubjectsMouseClicked

    private void btnSubjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseEntered
        // TODO add your handling code here:
        if(pnlSubjects.getBackground().equals(new Color(157,12,12)))
            pnlSubjects.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnSubjectsMouseEntered

    private void btnSubjectsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlSubjects.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnSubjectsMouseExited

    private void btnSubjSchedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjSchedMouseClicked
        // TODO add your handling code here:
        ss.setVisible(true);
        cs.setVisible(false);
        sj.setVisible(false);
        em.setVisible(false);
        sy.setVisible(false);
        st.setVisible(false);
        db.setVisible(false);
        sg.setVisible(false);
        cl.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(135, 10, 10));
        pnlStudGrade.setBackground(new Color(157, 12, 12));
    }//GEN-LAST:event_btnSubjSchedMouseClicked

    private void btnSubjSchedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjSchedMouseEntered
        // TODO add your handling code here:
        if(pnlSubjSched.getBackground().equals(new Color(157,12,12)))
            pnlSubjSched.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnSubjSchedMouseEntered

    private void btnSubjSchedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjSchedMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10))
            || pnlStudGrade.getBackground().equals(new Color(135,10,10)))
                pnlSubjSched.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnSubjSchedMouseExited

    private void btnStudGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudGradeMouseClicked
        // TODO add your handling code here:
        sg.setVisible(true);
        ss.setVisible(false);
        cs.setVisible(false);
        sj.setVisible(false);
        em.setVisible(false);
        sy.setVisible(false);
        st.setVisible(false);
        db.setVisible(false);
        cl.setVisible(false);
        pnlDashboard.setBackground(new Color(157, 12, 12));
        pnlStudents.setBackground(new Color(157, 12, 12));
        pnlEmployees.setBackground(new Color(157, 12, 12));
        pnlSYSem.setBackground(new Color(157, 12, 12));
        pnlColleges.setBackground(new Color(157, 12, 12));
        pnlCourses.setBackground(new Color(157, 12, 12));
        pnlSubjects.setBackground(new Color(157, 12, 12));
        pnlSubjSched.setBackground(new Color(157, 12, 12));
        pnlStudGrade.setBackground(new Color(135, 10, 10));
        sg.sgv.populateTbl();
    }//GEN-LAST:event_btnStudGradeMouseClicked

    private void btnStudGradeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudGradeMouseEntered
        // TODO add your handling code here:
        if(pnlStudGrade.getBackground().equals(new Color(157,12,12)))
            pnlStudGrade.setBackground(new Color(135,10,10));
    }//GEN-LAST:event_btnStudGradeMouseEntered

    private void btnStudGradeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudGradeMouseExited
        // TODO add your handling code here:
        if(pnlDashboard.getBackground().equals(new Color(135,10,10))
            || pnlEmployees.getBackground().equals(new Color(135,10,10))
            || pnlSYSem.getBackground().equals(new Color(135,10,10))
            || pnlColleges.getBackground().equals(new Color(135,10,10))
            || pnlCourses.getBackground().equals(new Color(135,10,10))
            || pnlSubjects.getBackground().equals(new Color(135,10,10))
            || pnlSubjSched.getBackground().equals(new Color(135,10,10))
            || pnlStudents.getBackground().equals(new Color(135,10,10)))
                pnlStudGrade.setBackground(new Color(157,12,12));
    }//GEN-LAST:event_btnStudGradeMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //        populateTbl();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane MSCard;
    private javax.swing.JLabel btnColleges;
    public javax.swing.JLabel btnCourses;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnEmployees;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnSYSem;
    private javax.swing.JLabel btnStudGrade;
    private javax.swing.JLabel btnStudents;
    private javax.swing.JLabel btnSubjSched;
    private javax.swing.JLabel btnSubjects;
    private javax.swing.JLabel headerLogo;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JLabel lblMenuHeader;
    private studentrecords.RoundedFrame pnlColleges;
    private studentrecords.RoundedFrame pnlCourses;
    private studentrecords.RoundedFrame pnlDashboard;
    private studentrecords.RoundedFrame pnlEmployees;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMinimize;
    private studentrecords.RoundedFrame pnlSYSem;
    private studentrecords.RoundedFrame pnlStudGrade;
    private studentrecords.RoundedFrame pnlStudents;
    private studentrecords.RoundedFrame pnlSubjSched;
    private studentrecords.RoundedFrame pnlSubjects;
    // End of variables declaration//GEN-END:variables

    private void testData(JTable tblSched) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
