/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentrecords;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Joan
 */
public class SubjectScheduleAdd extends javax.swing.JPanel {

    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    /**
     * Creates new form Dashboard
     */
    public SubjectScheduleAdd() {
        initComponents();
        
        tblScheduleOptions.getTableHeader().setDefaultRenderer(new TableHeader());
        tblScheduleOptions.getTableHeader().setPreferredSize(new Dimension(0,40));
        
        populateTbl();
    }
    
    private class TableHeader extends DefaultTableCellRenderer {
        
        @Override
        public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
            Component com = super.getTableCellRendererComponent(jtable, o, bln1, bln1, i, i1);
            com.setBackground(new Color(157,12,12));
            com.setForeground(Color.white);
            com.setFont(com.getFont().deriveFont(Font.BOLD, 10));
            return com;
        }
    }
    
    public void populateTbl() {
        try {
            con = ConnectDB.Connect();
            ps = con.prepareStatement("SELECT * FROM vw_subject_schedule ORDER BY \"School Year\"");
            rs = ps.executeQuery();
            tblScheduleOptions.setModel(DbUtils.resultSetToTableModel(rs));
            
            float[] floatRelativeWidths = {0.08f, 0.05f, 0.05f, 0.05f, 0.08f, 0.15f, 0.02f, 0.05f, 0.03f, 0.05f, 0.04f, 0.04f, 0.07f};
            int intTotalWidth = tblScheduleOptions.getWidth();
            for (int intCounter = 0; intCounter < tblScheduleOptions.getColumnCount(); intCounter++) {
                int intColumnWidth = (int) (intTotalWidth * floatRelativeWidths[intCounter]); // Calculate width as a fraction of the total width
                tblScheduleOptions.getColumnModel().getColumn(intCounter).setPreferredWidth(intColumnWidth);
            }
            
            rs.close();
            ps.close();
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public void clearFields() {
        //txtEmployeeID.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblScheduleOptions = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(240, 241, 243));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        tblScheduleOptions.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblScheduleOptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblScheduleOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblScheduleOptions.setFocusable(false);
        tblScheduleOptions.setRowHeight(50);
        tblScheduleOptions.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblScheduleOptions.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblScheduleOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblScheduleOptionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblScheduleOptions);
        if (tblScheduleOptions.getColumnModel().getColumnCount() > 0) {
            tblScheduleOptions.getColumnModel().getColumn(0).setResizable(false);
            tblScheduleOptions.getColumnModel().getColumn(1).setResizable(false);
            tblScheduleOptions.getColumnModel().getColumn(2).setResizable(false);
            tblScheduleOptions.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblScheduleOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScheduleOptionsMouseClicked

    }//GEN-LAST:event_tblScheduleOptionsMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        tblScheduleOptions.clearSelection();
        clearFields();
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblScheduleOptions;
    // End of variables declaration//GEN-END:variables
}
