/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentrecords;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Joan
 */
public class SubjectScheduleDayView extends javax.swing.JPanel {

    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    /**
     * Creates new form Dashboard
     */
    public SubjectScheduleDayView() {
        initComponents();
        
        tblMonday.getTableHeader().setDefaultRenderer(new TableHeader());
        tblMonday.getTableHeader().setPreferredSize(new Dimension(0,40));
        
        tblTuesday.getTableHeader().setDefaultRenderer(new TableHeader());
        tblTuesday.getTableHeader().setPreferredSize(new Dimension(0,40));
        
        tblWednesday.getTableHeader().setDefaultRenderer(new TableHeader());
        tblWednesday.getTableHeader().setPreferredSize(new Dimension(0,40));
        
        tblThursday.getTableHeader().setDefaultRenderer(new TableHeader());
        tblThursday.getTableHeader().setPreferredSize(new Dimension(0, 40));

        tblFriday.getTableHeader().setDefaultRenderer(new TableHeader());
        tblFriday.getTableHeader().setPreferredSize(new Dimension(0, 40));

        tblSaturday.getTableHeader().setDefaultRenderer(new TableHeader());
        tblSaturday.getTableHeader().setPreferredSize(new Dimension(0, 40));
        
        populateTbl();
    }
    
    private class TableHeader extends DefaultTableCellRenderer {
        
        @Override
        public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
            Component com = super.getTableCellRendererComponent(jtable, o, bln1, bln1, i, i1);
            com.setBackground(new Color(157,12,12));
            com.setForeground(Color.white);
            com.setFont(com.getFont().deriveFont(Font.BOLD, 10));
            return com;
        }
    }
    
    public void populateTbl() {
        try {
            con = ConnectDB.Connect();
            
            ps = con.prepareStatement("SELECT * FROM vw_schedule_mon ORDER BY \"Sequence No\"");
            rs = ps.executeQuery();
            tblMonday.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            
            ps = con.prepareStatement("SELECT * FROM vw_schedule_tue ORDER BY \"Sequence No\"");
            rs = ps.executeQuery();
            tblTuesday.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            
            ps = con.prepareStatement("SELECT * FROM vw_schedule_wed ORDER BY \"Sequence No\"");
            rs = ps.executeQuery();
            tblWednesday.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            
            ps = con.prepareStatement("SELECT * FROM vw_schedule_thu ORDER BY \"Sequence No\"");
            rs = ps.executeQuery();
            tblThursday.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            
            ps = con.prepareStatement("SELECT * FROM vw_schedule_fri ORDER BY \"Sequence No\"");
            rs = ps.executeQuery();
            tblFriday.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            
            ps = con.prepareStatement("SELECT * FROM vw_schedule_sat ORDER BY \"Sequence No\"");
            rs = ps.executeQuery();
            tblSaturday.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            ps.close();
            
            con.close();
        } catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public void clearFields() {
        //txtEmployeeID.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonday = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTuesday = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblWednesday = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThursday = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFriday = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSaturday = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(240, 241, 243));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        tblMonday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblMonday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblMonday.setFocusable(false);
        tblMonday.setRowHeight(50);
        tblMonday.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblMonday.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblMonday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMondayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonday);
        if (tblMonday.getColumnModel().getColumnCount() > 0) {
            tblMonday.getColumnModel().getColumn(0).setResizable(false);
            tblMonday.getColumnModel().getColumn(1).setResizable(false);
            tblMonday.getColumnModel().getColumn(2).setResizable(false);
            tblMonday.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Monday");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Tuesday");

        tblTuesday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblTuesday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTuesday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblTuesday.setFocusable(false);
        tblTuesday.setRowHeight(50);
        tblTuesday.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblTuesday.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblTuesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTuesdayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTuesday);
        if (tblTuesday.getColumnModel().getColumnCount() > 0) {
            tblTuesday.getColumnModel().getColumn(0).setResizable(false);
            tblTuesday.getColumnModel().getColumn(1).setResizable(false);
            tblTuesday.getColumnModel().getColumn(2).setResizable(false);
            tblTuesday.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Wednesday");

        tblWednesday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblWednesday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWednesday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblWednesday.setFocusable(false);
        tblWednesday.setRowHeight(50);
        tblWednesday.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblWednesday.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblWednesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWednesdayMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblWednesday);
        if (tblWednesday.getColumnModel().getColumnCount() > 0) {
            tblWednesday.getColumnModel().getColumn(0).setResizable(false);
            tblWednesday.getColumnModel().getColumn(1).setResizable(false);
            tblWednesday.getColumnModel().getColumn(2).setResizable(false);
            tblWednesday.getColumnModel().getColumn(3).setResizable(false);
        }

        tblThursday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblThursday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThursday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblThursday.setFocusable(false);
        tblThursday.setRowHeight(50);
        tblThursday.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblThursday.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblThursday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThursdayMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblThursday);
        if (tblThursday.getColumnModel().getColumnCount() > 0) {
            tblThursday.getColumnModel().getColumn(0).setResizable(false);
            tblThursday.getColumnModel().getColumn(1).setResizable(false);
            tblThursday.getColumnModel().getColumn(2).setResizable(false);
            tblThursday.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Thursday");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Friday");

        tblFriday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblFriday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFriday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblFriday.setFocusable(false);
        tblFriday.setRowHeight(50);
        tblFriday.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblFriday.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblFriday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFridayMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblFriday);
        if (tblFriday.getColumnModel().getColumnCount() > 0) {
            tblFriday.getColumnModel().getColumn(0).setResizable(false);
            tblFriday.getColumnModel().getColumn(1).setResizable(false);
            tblFriday.getColumnModel().getColumn(2).setResizable(false);
            tblFriday.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Saturday");

        tblSaturday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblSaturday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSaturday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblSaturday.setFocusable(false);
        tblSaturday.setRowHeight(50);
        tblSaturday.setSelectionBackground(new java.awt.Color(239, 225, 225));
        tblSaturday.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblSaturday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSaturdayMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblSaturday);
        if (tblSaturday.getColumnModel().getColumnCount() > 0) {
            tblSaturday.getColumnModel().getColumn(0).setResizable(false);
            tblSaturday.getColumnModel().getColumn(1).setResizable(false);
            tblSaturday.getColumnModel().getColumn(2).setResizable(false);
            tblSaturday.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(0, 168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        tblMonday.clearSelection();
        clearFields();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void tblMondayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMondayMouseClicked

    }//GEN-LAST:event_tblMondayMouseClicked

    private void tblTuesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTuesdayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTuesdayMouseClicked

    private void tblWednesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWednesdayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblWednesdayMouseClicked

    private void tblThursdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThursdayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblThursdayMouseClicked

    private void tblFridayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFridayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblFridayMouseClicked

    private void tblSaturdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSaturdayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSaturdayMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable tblFriday;
    public javax.swing.JTable tblMonday;
    public javax.swing.JTable tblSaturday;
    public javax.swing.JTable tblThursday;
    public javax.swing.JTable tblTuesday;
    public javax.swing.JTable tblWednesday;
    // End of variables declaration//GEN-END:variables
}
